In [1]:
%matplotlib inline
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt

In [2]:
data = np.loadtxt("data/data3a.csv",delimiter=",", skiprows=1, usecols=(0, 1), dtype=np.float32)

In [3]:
csv = spark.read.option(
    "inferSchema", "true").option(
    "header", "true").csv("data/data3a.csv")

In [6]:
csv.toPandas()

     y      x  f
0    6   8.31  C
1    6   9.44  C
2    6   9.50  C
3   12   9.07  C
4   10  10.16  C
5    4   8.32  C
6    9  10.61  C
7    9  10.06  C
8    9   9.93  C
9   11  10.43  C
10   6  10.36  C
11  10  10.15  C
12   6  10.92  C
13  10   8.85  C
14  11   9.42  C
15   8  11.11  C
16   3   8.02  C
17   8  11.93  C
18   5   8.55  C
19   5   7.19  C
20   4   9.83  C
21  11  10.79  C
22   5   8.89  C
23  10  10.09  C
24   6  11.63  C
25   6  10.21  C
26   7   9.45  C
27   9  10.44  C
28   3   9.44  C
29  10  10.48  C
..  ..    ... ..
70  10  10.54  T
71   8  11.30  T
72   8  12.40  T
73   7  10.18  T
74   5   9.53  T
75   6  10.24  T
76   8  11.76  T
77   9   9.52  T
78   9  10.40  T
79   6   9.96  T
80   7  10.30  T
81  10  11.54  T
82   6   9.42  T
83  11  11.28  T
84  11   9.73  T
85  11  10.78  T
86   5  10.21  T
87   6  10.51  T
88   4  10.73  T
89   5   8.85  T
90   6  11.20  T
91   5   9.86  T
92   8  11.54  T
93   5  10.03  T
94   9  11.88  T
95   8   9.15  T
96   6   8.52  T
97   8  10.24  T
98   7  10.86  T
99   9   9.97  T

[100 rows x 3 columns]